### ISSUE TITLE
고급 영어 숙제

### ISSUE THREAD

**Issue by kcm1700** [simnalamburt/snucse#1]
#### Done
- [x] kcm이 준 docx파일 정리해서 필기하기
- [x] 화요일에 주어진 숙제 (docx 안에 써있음) 하기
- [x] 자주쓰는 영어표현 익히기 [img1](https://cloud.githubusercontent.com/assets/998122/13636210/ff6ccae4-e643-11e5-97e3-eea2a32a987c.jpg) [img2](https://cloud.githubusercontent.com/assets/998122/13636211/ff720cd4-e643-11e5-8b3d-cdf0cde7f7ba.jpg)
- [x] [학교 밖에서 행아웃으로 만나기](http://etl.snu.ac.kr/mod/forum/view.php?id=415661)
- 동성애
  - [Coming Home: Queer South Asians and the Politics of Family](http://returnthegayze.com/2014/07/28/coming-home-queer-south-asians-and-the-politics/) (Optional)
  - [x] [Love, no matter what](https://www.ted.com/talks/andrew_solomon_love_no_matter_what#t-15982)
  - [x] Out and About Coming of Age in a straight White World, [다운로드](https://github.com/simnalamburt/snucse/files/175731/a.pdf)
  - [x] [다음 이야기 주제 미리 생각해오기](http://etl.snu.ac.kr/mod/forum/view.php?id=416265)
- 3월 31일까지
  - [x] 이민자들에 관한 숙제
  - [x] Life and Debt (2001) 보기
- [x] IMF 조사하기
- Linked Session 후기 쓰기
  - [x] 토요일 점심까지 목요일날 했던 경험에 대한 소감을 4~6문장 정도 쓰기
  - [x] 다음 수업시간까지 남의 글에 답변을 두 개 달기. 각각 3~5문장으로 할 것
- [x] 한국인이 외국인에 대해 갖는 열가지 스테레오타입
- [x] 외국인이 한국인에 대해 갖는 열가지 스테레오타입
- [x] 파이널 리포트에 쓸 주제 최소한 세가지 준비해오기
  - 미국사람들이 북한에 대해 가지는 인식에 관한거
  - 미국애들이 중동 분쟁에 대해 가지는 인식이 어떠한지
  - ISIS
  - 도널드 트럼프
  - 시리아 난민사태
  - 한국과 미국의 게이문화 차이
  - 군인문화차이
  - 한국과 미국의 직장문화 차이 <sup>Selected!</sup>
- [x] 마지막 링크드 세션 ETL에서 그룹 만들기. 애들이랑 페친맺으면 숙제할때 좋아.
- [x] <simnalamburt2@gmail.com> 지우기

**Comment by kcm1700** [comment]
![page1](https://cloud.githubusercontent.com/assets/998122/13636210/ff6ccae4-e643-11e5-97e3-eea2a32a987c.jpg)
![page2](https://cloud.githubusercontent.com/assets/998122/13636211/ff720cd4-e643-11e5-8b3d-cdf0cde7f7ba.jpg)

**Comment by simnalamburt** [comment]
숙제가 있음

**Comment by simnalamburt** [comment]
> **숙제1**

Missed Session 1
========

Hi my name is Hyeon Kim, and I missed the linked session 1. Though I heard that I should write about my experiences that I had at last Thursday, I hereby write my own experiences.

I went Indonesia to experience total solar eclipse last week and at the last Thursday I was on the returning flight. I have been on various flights but such uncrowded flight was actually the first time for me. The flight had almost no passenger so that almost everyone in that flight could use 4 adjacent seats at once as a bed. So I could return to Korea with a very nice sleep.

When I landed to 인천 airport it was 9:20 AM so I counldn't help attending class. I arrived SNU at 12:00 PM and eventually I missed all classes in this week, but it was valuable experience enough. If you want to heard about the total eclipse, let's meet at next linked session.

**Comment by pse1202** [comment]
Hi my name is Hyeon Kim, and I missed the linked session 1. However, I heard that I should write about my experiences that I had on last Thursday, so I would like to do so.

**Comment by simnalamburt** [comment]
### 영어 표현 외우기
##### 의견 제시
- **It seems to me that** kcm is the one of the best programmer in the world
- **As I see it,** kcm does his homework diligently
- **It seems clear that** kcm is the one of the greatest programmer in the CS history
- **Well, In my opinion,** kcm is the one who no one can be match for
- **Well, as far as I'm concerned,** letting kcm to leave in Korea is a great waste
- **I think most people would agree that** kcm is not only a great programmer but also a great computer scientist
- **To bring up another point,** kcm does play piano very well
- **There's no doubt in my mind that** kcm is the one who have a great mind
- **I'm convinced that** kcm is not the one who can be easily found
- **I'd also like to point out that** kcm is very kind person
- **I'd like to mention that** kcm is very kind person

##### 동의
- That's a good point
- I agree with you completely
- I couldn't agree more.
- I agree entirely with that point of view
- That's my feeling exactly
- I'd like to add to what said. I think Rust is amazing programming language
- I think we are in agreement about that
- My point is similar to kcm's point: Rust is the PL that shows how we should do programming in the 21st century

##### 부분 동의/부분 반대
- **By and large, I would accept your views, but** Windows sucks
- **That may be true, but** we shouldn't really use php in production anymore
- **Generally speaking, I agree with you, but it could also be said that** PLs which created before 21st century sucks in someway
- **I accept that in theory, but** no one would be suffer if that really worked out in theory
- **I agree in principle, but** it doesn't operate as principle in real world
- **Although I agree with most of what you've said, I find it difficult to agree with you point about** your admiration toward C

##### Expressing polite disagreement
- **Yes, but don't you think that** I'm right?
- **I see your argument, but** I cannot agree
- **But surely** Windows sucks
- **I'm not sure I agree with you on that. What I think is that** programmers in open source society should be very nice to others
- **I think I understand your perspective, but** you are not Torvalds and you didn't make Linux so your arrogance cannot be excused
- **Perhaps. But what about** Guido van Rossum?
- **I'm afraid I have to disagree with you because** I think the essence of OSS should not be harmed by Meritocracy
- **I have some sympathy for you position, but** you should quit your business if you cannot afford your employee's minimum wage
- **Yes, that may be true, but** also that can be false
- **I'm not totally convinced by your argument.**

##### 재확인
- **I didn't follow what you said about** Turing machine
- **I'm sorry, but I didn't get your last point. Could you go over that again?**
- **What exactly do you mean by**

**Comment by simnalamburt** [comment]
### 숙제2
- Quite amazing that each of you didn't have enough time, hope you enjoyed though. And it's interesting that three of your team member can speak Japanese. Hope to know how polular the japanese in among American society.
- Quite amazing that they do not choose their major before entering university. I wonder if all universities of America use such policy. And also it's so amazing that more than one people in your team can use and understant sign language. I didn't even know that I can be internationally used.
